import type { Solid, SolidDecorDensity, TerrainMaterial } from "./types";

export const TERRAIN_DECOR_PROP_TEXTURE_PREFIX = "terrain-decor-prop";

export const solidDecorDensityValues = ["auto", "off", "low", "medium", "high"] as const satisfies readonly SolidDecorDensity[];

export const solidDecorDensityLabels: Record<SolidDecorDensity, string> = {
  auto: "Auto",
  off: "Off",
  low: "Low",
  medium: "Medium",
  high: "High"
};

export type TerrainDecorPropCategory =
  | "surface-small"
  | "surface-medium"
  | "behind-surface-large"
  | "overhang"
  | "wall-decal";

export type TerrainDecorAnchor = "bottom-left" | "bottom-center" | "top-left" | "wall-left";

export type TerrainDecorPropDefinition = {
  id: string;
  material: TerrainMaterial;
  category: TerrainDecorPropCategory;
  frame: number;
  w: number;
  h: number;
  anchor: TerrainDecorAnchor;
  minSegmentWidth: number;
  clearance: { w: number; h: number };
  densities: ReadonlyArray<Exclude<SolidDecorDensity, "auto" | "off">>;
  weight: number;
  depthOffset: number;
};

const automaticDecorDensityByMaterial: Partial<Record<TerrainMaterial, Exclude<SolidDecorDensity, "auto" | "off">>> = {
  "grass-organic": "medium",
  "copper-corrode": "medium",
  "warning-industrial": "low",
  "ice-cryo": "medium",
  "wood-archive": "medium"
};

export const normalizeSolidDecorDensity = (value: unknown): SolidDecorDensity | undefined =>
  solidDecorDensityValues.includes(value as SolidDecorDensity) ? (value as SolidDecorDensity) : undefined;

export const terrainDecorPropTextureKey = (prop: Pick<TerrainDecorPropDefinition, "id">): string =>
  `${TERRAIN_DECOR_PROP_TEXTURE_PREFIX}:${prop.id}`;

export const terrainDecorPropSrc = (prop: Pick<TerrainDecorPropDefinition, "id">): string =>
  `/assets/sprites/terrain-decor-props/${prop.id}.png`;

export const effectiveSolidDecorDensity = (
  solid: Pick<Solid, "decorDensity">,
  material: TerrainMaterial
): SolidDecorDensity => {
  const density = normalizeSolidDecorDensity(solid.decorDensity) || "auto";
  if (density !== "auto") return density;
  return automaticDecorDensityByMaterial[material] || "off";
};

export const gardenTerrainDecorProps = [
  {
    id: "grass-tufts",
    material: "grass-organic",
    category: "surface-small",
    frame: 0,
    w: 56,
    h: 44,
    anchor: "bottom-left",
    minSegmentWidth: 48,
    clearance: { w: 50, h: 36 },
    densities: ["low", "medium", "high"],
    weight: 4,
    depthOffset: 0.21
  },
  {
    id: "wildflower-cluster",
    material: "grass-organic",
    category: "surface-small",
    frame: 1,
    w: 54,
    h: 42,
    anchor: "bottom-left",
    minSegmentWidth: 56,
    clearance: { w: 48, h: 36 },
    densities: ["low", "medium", "high"],
    weight: 3,
    depthOffset: 0.22
  },
  {
    id: "mushroom-pair",
    material: "grass-organic",
    category: "surface-small",
    frame: 2,
    w: 68,
    h: 48,
    anchor: "bottom-left",
    minSegmentWidth: 80,
    clearance: { w: 62, h: 42 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.21
  },
  {
    id: "sprout-leaves",
    material: "grass-organic",
    category: "surface-small",
    frame: 3,
    w: 56,
    h: 45,
    anchor: "bottom-left",
    minSegmentWidth: 48,
    clearance: { w: 50, h: 38 },
    densities: ["low", "medium", "high"],
    weight: 3,
    depthOffset: 0.21
  },
  {
    id: "moss-stone",
    material: "grass-organic",
    category: "surface-small",
    frame: 4,
    w: 82,
    h: 37,
    anchor: "bottom-left",
    minSegmentWidth: 72,
    clearance: { w: 74, h: 32 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.2
  },
  {
    id: "root-curl",
    material: "grass-organic",
    category: "surface-small",
    frame: 5,
    w: 55,
    h: 45,
    anchor: "bottom-left",
    minSegmentWidth: 72,
    clearance: { w: 50, h: 40 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.2
  },
  {
    id: "fern-cluster",
    material: "grass-organic",
    category: "surface-medium",
    frame: 6,
    w: 76,
    h: 70,
    anchor: "bottom-center",
    minSegmentWidth: 112,
    clearance: { w: 68, h: 62 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.18
  },
  {
    id: "flowering-shrub",
    material: "grass-organic",
    category: "surface-medium",
    frame: 7,
    w: 86,
    h: 78,
    anchor: "bottom-center",
    minSegmentWidth: 124,
    clearance: { w: 78, h: 70 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.18
  },
  {
    id: "leaf-bush",
    material: "grass-organic",
    category: "surface-medium",
    frame: 8,
    w: 86,
    h: 77,
    anchor: "bottom-center",
    minSegmentWidth: 132,
    clearance: { w: 78, h: 68 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.17
  },
  {
    id: "root-mound",
    material: "grass-organic",
    category: "surface-medium",
    frame: 9,
    w: 82,
    h: 57,
    anchor: "bottom-center",
    minSegmentWidth: 112,
    clearance: { w: 74, h: 50 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.16
  },
  {
    id: "slim-tree",
    material: "grass-organic",
    category: "behind-surface-large",
    frame: 10,
    w: 113,
    h: 150,
    anchor: "bottom-center",
    minSegmentWidth: 180,
    clearance: { w: 104, h: 140 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: -0.24
  },
  {
    id: "broad-tree",
    material: "grass-organic",
    category: "behind-surface-large",
    frame: 11,
    w: 119,
    h: 160,
    anchor: "bottom-center",
    minSegmentWidth: 240,
    clearance: { w: 108, h: 148 },
    densities: ["high"],
    weight: 2,
    depthOffset: -0.26
  },
  {
    id: "root-arch",
    material: "grass-organic",
    category: "behind-surface-large",
    frame: 12,
    w: 160,
    h: 100,
    anchor: "bottom-center",
    minSegmentWidth: 260,
    clearance: { w: 148, h: 92 },
    densities: ["high"],
    weight: 1,
    depthOffset: -0.25
  },
  {
    id: "hanging-vines",
    material: "grass-organic",
    category: "overhang",
    frame: 13,
    w: 68,
    h: 90,
    anchor: "top-left",
    minSegmentWidth: 112,
    clearance: { w: 60, h: 80 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.08
  },
  {
    id: "dangling-roots",
    material: "grass-organic",
    category: "overhang",
    frame: 14,
    w: 58,
    h: 88,
    anchor: "top-left",
    minSegmentWidth: 96,
    clearance: { w: 50, h: 78 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.08
  },
  {
    id: "moss-strip",
    material: "grass-organic",
    category: "overhang",
    frame: 15,
    w: 78,
    h: 32,
    anchor: "top-left",
    minSegmentWidth: 128,
    clearance: { w: 70, h: 28 },
    densities: ["high"],
    weight: 2,
    depthOffset: 0.08
  },
  {
    id: "wall-vine",
    material: "grass-organic",
    category: "wall-decal",
    frame: 16,
    w: 40,
    h: 185,
    anchor: "wall-left",
    minSegmentWidth: 96,
    clearance: { w: 34, h: 170 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.06
  },
  {
    id: "root-creeper",
    material: "grass-organic",
    category: "wall-decal",
    frame: 17,
    w: 62,
    h: 180,
    anchor: "wall-left",
    minSegmentWidth: 128,
    clearance: { w: 54, h: 166 },
    densities: ["high"],
    weight: 2,
    depthOffset: 0.06
  },
  {
    id: "tiny-flower-tuft",
    material: "grass-organic",
    category: "surface-small",
    frame: 18,
    w: 60,
    h: 48,
    anchor: "bottom-left",
    minSegmentWidth: 64,
    clearance: { w: 54, h: 42 },
    densities: ["low", "medium", "high"],
    weight: 3,
    depthOffset: 0.22
  },
  {
    id: "glow-moss-clump",
    material: "grass-organic",
    category: "surface-small",
    frame: 19,
    w: 78,
    h: 38,
    anchor: "bottom-left",
    minSegmentWidth: 72,
    clearance: { w: 70, h: 32 },
    densities: ["low", "medium", "high"],
    weight: 3,
    depthOffset: 0.2
  },
  {
    id: "seedling-sprout",
    material: "grass-organic",
    category: "surface-small",
    frame: 20,
    w: 58,
    h: 56,
    anchor: "bottom-left",
    minSegmentWidth: 64,
    clearance: { w: 52, h: 50 },
    densities: ["low", "medium", "high"],
    weight: 2,
    depthOffset: 0.2
  },
  {
    id: "edge-leaf-clump",
    material: "grass-organic",
    category: "surface-small",
    frame: 21,
    w: 72,
    h: 44,
    anchor: "bottom-left",
    minSegmentWidth: 72,
    clearance: { w: 64, h: 38 },
    densities: ["low", "medium", "high"],
    weight: 3,
    depthOffset: 0.2
  },
  {
    id: "thin-fern-spray",
    material: "grass-organic",
    category: "surface-medium",
    frame: 22,
    w: 76,
    h: 74,
    anchor: "bottom-center",
    minSegmentWidth: 112,
    clearance: { w: 68, h: 66 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.18
  },
  {
    id: "curled-root-hook",
    material: "grass-organic",
    category: "surface-small",
    frame: 23,
    w: 58,
    h: 50,
    anchor: "bottom-left",
    minSegmentWidth: 72,
    clearance: { w: 52, h: 44 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.19
  },
  {
    id: "pink-flower-tuft",
    material: "grass-organic",
    category: "surface-medium",
    frame: 24,
    w: 74,
    h: 76,
    anchor: "bottom-center",
    minSegmentWidth: 112,
    clearance: { w: 66, h: 68 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.18
  },
  {
    id: "small-mushroom-pair",
    material: "grass-organic",
    category: "surface-small",
    frame: 25,
    w: 58,
    h: 62,
    anchor: "bottom-left",
    minSegmentWidth: 80,
    clearance: { w: 52, h: 56 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.2
  },
  {
    id: "meadow-flower-clump",
    material: "grass-organic",
    category: "surface-small",
    frame: 26,
    w: 76,
    h: 44,
    anchor: "bottom-left",
    minSegmentWidth: 76,
    clearance: { w: 68, h: 38 },
    densities: ["low", "medium", "high"],
    weight: 3,
    depthOffset: 0.21
  },
  {
    id: "curled-vine-sprout",
    material: "grass-organic",
    category: "surface-small",
    frame: 27,
    w: 52,
    h: 70,
    anchor: "bottom-left",
    minSegmentWidth: 76,
    clearance: { w: 46, h: 62 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.2
  },
  {
    id: "broken-root-nub",
    material: "grass-organic",
    category: "surface-medium",
    frame: 28,
    w: 78,
    h: 74,
    anchor: "bottom-center",
    minSegmentWidth: 112,
    clearance: { w: 70, h: 66 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.17
  },
  {
    id: "broad-leaf-tuft",
    material: "grass-organic",
    category: "surface-small",
    frame: 29,
    w: 72,
    h: 58,
    anchor: "bottom-left",
    minSegmentWidth: 76,
    clearance: { w: 64, h: 52 },
    densities: ["low", "medium", "high"],
    weight: 3,
    depthOffset: 0.2
  }
] as const satisfies readonly TerrainDecorPropDefinition[];

export const rainhouseTerrainDecorProps = [
  {
    id: "rain-copper-coil",
    material: "copper-corrode",
    category: "surface-small",
    frame: 30,
    w: 54,
    h: 72,
    anchor: "bottom-left",
    minSegmentWidth: 64,
    clearance: { w: 48, h: 64 },
    densities: ["low", "medium", "high"],
    weight: 3,
    depthOffset: 0.2
  },
  {
    id: "rain-patina-relay-box",
    material: "copper-corrode",
    category: "surface-medium",
    frame: 31,
    w: 92,
    h: 78,
    anchor: "bottom-center",
    minSegmentWidth: 124,
    clearance: { w: 82, h: 70 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.17
  },
  {
    id: "rain-wet-cable-loop",
    material: "copper-corrode",
    category: "surface-small",
    frame: 32,
    w: 76,
    h: 70,
    anchor: "bottom-left",
    minSegmentWidth: 88,
    clearance: { w: 68, h: 62 },
    densities: ["low", "medium", "high"],
    weight: 2,
    depthOffset: 0.19
  },
  {
    id: "rain-insulator-cluster",
    material: "copper-corrode",
    category: "surface-medium",
    frame: 33,
    w: 84,
    h: 96,
    anchor: "bottom-center",
    minSegmentWidth: 128,
    clearance: { w: 74, h: 86 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.16
  },
  {
    id: "rain-gutter-cap",
    material: "copper-corrode",
    category: "surface-medium",
    frame: 34,
    w: 112,
    h: 64,
    anchor: "bottom-center",
    minSegmentWidth: 150,
    clearance: { w: 100, h: 56 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.17
  },
  {
    id: "rain-dripping-pipes",
    material: "copper-corrode",
    category: "overhang",
    frame: 35,
    w: 74,
    h: 92,
    anchor: "top-left",
    minSegmentWidth: 112,
    clearance: { w: 66, h: 82 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.08
  },
  {
    id: "rain-warning-plate",
    material: "warning-industrial",
    category: "surface-small",
    frame: 36,
    w: 90,
    h: 42,
    anchor: "bottom-left",
    minSegmentWidth: 96,
    clearance: { w: 80, h: 36 },
    densities: ["low", "medium", "high"],
    weight: 4,
    depthOffset: 0.19
  },
  {
    id: "rain-glass-energy-node",
    material: "glass-energy",
    category: "surface-small",
    frame: 37,
    w: 64,
    h: 72,
    anchor: "bottom-left",
    minSegmentWidth: 80,
    clearance: { w: 56, h: 64 },
    densities: ["low", "medium", "high"],
    weight: 3,
    depthOffset: 0.18
  },
  {
    id: "rain-cable-bank",
    material: "copper-corrode",
    category: "overhang",
    frame: 38,
    w: 68,
    h: 116,
    anchor: "top-left",
    minSegmentWidth: 112,
    clearance: { w: 60, h: 104 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.08
  },
  {
    id: "rain-wall-conduit-panel",
    material: "glass-energy",
    category: "wall-decal",
    frame: 39,
    w: 112,
    h: 100,
    anchor: "wall-left",
    minSegmentWidth: 120,
    clearance: { w: 102, h: 90 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.05
  },
  {
    id: "rain-copper-column-fragment",
    material: "copper-corrode",
    category: "behind-surface-large",
    frame: 40,
    w: 70,
    h: 128,
    anchor: "bottom-center",
    minSegmentWidth: 170,
    clearance: { w: 62, h: 118 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: -0.22
  },
  {
    id: "rain-cracked-relay-cabinet",
    material: "copper-corrode",
    category: "behind-surface-large",
    frame: 41,
    w: 118,
    h: 128,
    anchor: "bottom-center",
    minSegmentWidth: 220,
    clearance: { w: 106, h: 118 },
    densities: ["high"],
    weight: 2,
    depthOffset: -0.24
  },
  {
    id: "rain-puddle-conduit",
    material: "copper-corrode",
    category: "surface-medium",
    frame: 42,
    w: 120,
    h: 52,
    anchor: "bottom-center",
    minSegmentWidth: 140,
    clearance: { w: 110, h: 46 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.16
  },
  {
    id: "rain-small-terminal",
    material: "copper-corrode",
    category: "surface-medium",
    frame: 43,
    w: 76,
    h: 100,
    anchor: "bottom-center",
    minSegmentWidth: 124,
    clearance: { w: 68, h: 90 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.16
  },
  {
    id: "rain-hanging-chain-cable",
    material: "warning-industrial",
    category: "overhang",
    frame: 44,
    w: 84,
    h: 118,
    anchor: "top-left",
    minSegmentWidth: 128,
    clearance: { w: 76, h: 106 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.08
  },
  {
    id: "rain-relay-mast",
    material: "copper-corrode",
    category: "behind-surface-large",
    frame: 45,
    w: 132,
    h: 158,
    anchor: "bottom-center",
    minSegmentWidth: 260,
    clearance: { w: 120, h: 146 },
    densities: ["high"],
    weight: 1,
    depthOffset: -0.25
  }
] as const satisfies readonly TerrainDecorPropDefinition[];

export const cryoTerrainDecorProps = [
  {
    id: "cryo-frost-clump",
    material: "ice-cryo",
    category: "surface-small",
    frame: 46,
    w: 72,
    h: 48,
    anchor: "bottom-left",
    minSegmentWidth: 72,
    clearance: { w: 64, h: 42 },
    densities: ["low", "medium", "high"],
    weight: 4,
    depthOffset: 0.21
  },
  {
    id: "cryo-ice-shard-cluster",
    material: "ice-cryo",
    category: "surface-medium",
    frame: 47,
    w: 86,
    h: 86,
    anchor: "bottom-center",
    minSegmentWidth: 118,
    clearance: { w: 76, h: 78 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.17
  },
  {
    id: "cryo-frozen-cable-stub",
    material: "ice-cryo",
    category: "surface-small",
    frame: 48,
    w: 70,
    h: 82,
    anchor: "bottom-left",
    minSegmentWidth: 86,
    clearance: { w: 62, h: 74 },
    densities: ["low", "medium", "high"],
    weight: 2,
    depthOffset: 0.19
  },
  {
    id: "cryo-small-canister",
    material: "ice-cryo",
    category: "surface-medium",
    frame: 49,
    w: 64,
    h: 98,
    anchor: "bottom-center",
    minSegmentWidth: 112,
    clearance: { w: 56, h: 88 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.16
  },
  {
    id: "cryo-snow-crystal-mound",
    material: "ice-cryo",
    category: "surface-small",
    frame: 50,
    w: 80,
    h: 48,
    anchor: "bottom-left",
    minSegmentWidth: 82,
    clearance: { w: 72, h: 42 },
    densities: ["low", "medium", "high"],
    weight: 3,
    depthOffset: 0.2
  },
  {
    id: "cryo-frosted-vent",
    material: "ice-cryo",
    category: "surface-medium",
    frame: 51,
    w: 98,
    h: 78,
    anchor: "bottom-center",
    minSegmentWidth: 132,
    clearance: { w: 88, h: 70 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.16
  },
  {
    id: "cryo-cold-warning-plate",
    material: "ice-cryo",
    category: "surface-small",
    frame: 52,
    w: 90,
    h: 46,
    anchor: "bottom-left",
    minSegmentWidth: 96,
    clearance: { w: 80, h: 40 },
    densities: ["low", "medium", "high"],
    weight: 2,
    depthOffset: 0.19
  },
  {
    id: "cryo-glow-core-node",
    material: "ice-cryo",
    category: "surface-small",
    frame: 53,
    w: 70,
    h: 76,
    anchor: "bottom-left",
    minSegmentWidth: 86,
    clearance: { w: 62, h: 68 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.18
  },
  {
    id: "cryo-hanging-icicles",
    material: "ice-cryo",
    category: "overhang",
    frame: 54,
    w: 86,
    h: 100,
    anchor: "top-left",
    minSegmentWidth: 112,
    clearance: { w: 78, h: 90 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.08
  },
  {
    id: "cryo-frozen-cable-bundle",
    material: "ice-cryo",
    category: "overhang",
    frame: 55,
    w: 72,
    h: 110,
    anchor: "top-left",
    minSegmentWidth: 112,
    clearance: { w: 64, h: 100 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.08
  },
  {
    id: "cryo-wall-frost-crack",
    material: "ice-cryo",
    category: "wall-decal",
    frame: 56,
    w: 110,
    h: 100,
    anchor: "wall-left",
    minSegmentWidth: 120,
    clearance: { w: 100, h: 90 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.05
  },
  {
    id: "cryo-frozen-glass-panel",
    material: "ice-cryo",
    category: "wall-decal",
    frame: 57,
    w: 110,
    h: 108,
    anchor: "wall-left",
    minSegmentWidth: 128,
    clearance: { w: 100, h: 98 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.05
  },
  {
    id: "cryo-tall-tank",
    material: "ice-cryo",
    category: "behind-surface-large",
    frame: 58,
    w: 82,
    h: 140,
    anchor: "bottom-center",
    minSegmentWidth: 180,
    clearance: { w: 74, h: 128 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: -0.23
  },
  {
    id: "cryo-ice-column-fragment",
    material: "ice-cryo",
    category: "behind-surface-large",
    frame: 59,
    w: 76,
    h: 138,
    anchor: "bottom-center",
    minSegmentWidth: 170,
    clearance: { w: 68, h: 126 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: -0.22
  },
  {
    id: "cryo-background-pod",
    material: "ice-cryo",
    category: "behind-surface-large",
    frame: 60,
    w: 150,
    h: 100,
    anchor: "bottom-center",
    minSegmentWidth: 260,
    clearance: { w: 138, h: 90 },
    densities: ["high"],
    weight: 1,
    depthOffset: -0.25
  },
  {
    id: "cryo-hanging-frost-cables",
    material: "ice-cryo",
    category: "overhang",
    frame: 61,
    w: 90,
    h: 130,
    anchor: "top-left",
    minSegmentWidth: 128,
    clearance: { w: 82, h: 118 },
    densities: ["high"],
    weight: 2,
    depthOffset: 0.08
  }
] as const satisfies readonly TerrainDecorPropDefinition[];

export const woodArchiveTerrainDecorProps = [
  {
    id: "timber-loose-papers",
    material: "wood-archive",
    category: "surface-small",
    frame: 62,
    w: 88,
    h: 60,
    anchor: "bottom-left",
    minSegmentWidth: 88,
    clearance: { w: 78, h: 52 },
    densities: ["low", "medium", "high"],
    weight: 4,
    depthOffset: 0.2
  },
  {
    id: "timber-tiny-book-stack",
    material: "wood-archive",
    category: "surface-small",
    frame: 63,
    w: 76,
    h: 72,
    anchor: "bottom-left",
    minSegmentWidth: 86,
    clearance: { w: 68, h: 64 },
    densities: ["low", "medium", "high"],
    weight: 3,
    depthOffset: 0.2
  },
  {
    id: "timber-glow-moss-log",
    material: "wood-archive",
    category: "surface-small",
    frame: 64,
    w: 88,
    h: 76,
    anchor: "bottom-left",
    minSegmentWidth: 96,
    clearance: { w: 78, h: 68 },
    densities: ["low", "medium", "high"],
    weight: 3,
    depthOffset: 0.2
  },
  {
    id: "timber-brass-data-tags",
    material: "wood-archive",
    category: "surface-small",
    frame: 65,
    w: 74,
    h: 76,
    anchor: "bottom-left",
    minSegmentWidth: 88,
    clearance: { w: 66, h: 68 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.19
  },
  {
    id: "timber-book-pile",
    material: "wood-archive",
    category: "surface-medium",
    frame: 66,
    w: 100,
    h: 112,
    anchor: "bottom-center",
    minSegmentWidth: 132,
    clearance: { w: 90, h: 100 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.16
  },
  {
    id: "timber-broken-shelf-chunk",
    material: "wood-archive",
    category: "surface-medium",
    frame: 67,
    w: 98,
    h: 122,
    anchor: "bottom-center",
    minSegmentWidth: 132,
    clearance: { w: 88, h: 110 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.16
  },
  {
    id: "timber-archive-crate",
    material: "wood-archive",
    category: "surface-medium",
    frame: 68,
    w: 94,
    h: 114,
    anchor: "bottom-center",
    minSegmentWidth: 128,
    clearance: { w: 84, h: 102 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.16
  },
  {
    id: "timber-root-data-box",
    material: "wood-archive",
    category: "surface-medium",
    frame: 69,
    w: 108,
    h: 122,
    anchor: "bottom-center",
    minSegmentWidth: 148,
    clearance: { w: 98, h: 110 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.16
  },
  {
    id: "timber-old-bookcase",
    material: "wood-archive",
    category: "behind-surface-large",
    frame: 70,
    w: 110,
    h: 158,
    anchor: "bottom-center",
    minSegmentWidth: 210,
    clearance: { w: 100, h: 146 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: -0.25
  },
  {
    id: "timber-timber-column",
    material: "wood-archive",
    category: "behind-surface-large",
    frame: 71,
    w: 74,
    h: 150,
    anchor: "bottom-center",
    minSegmentWidth: 170,
    clearance: { w: 66, h: 138 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: -0.23
  },
  {
    id: "timber-root-archive-trunk",
    material: "wood-archive",
    category: "behind-surface-large",
    frame: 72,
    w: 124,
    h: 140,
    anchor: "bottom-center",
    minSegmentWidth: 240,
    clearance: { w: 112, h: 128 },
    densities: ["high"],
    weight: 2,
    depthOffset: -0.25
  },
  {
    id: "timber-archive-terminal",
    material: "wood-archive",
    category: "behind-surface-large",
    frame: 73,
    w: 106,
    h: 140,
    anchor: "bottom-center",
    minSegmentWidth: 220,
    clearance: { w: 96, h: 128 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: -0.24
  },
  {
    id: "timber-dangling-roots",
    material: "wood-archive",
    category: "overhang",
    frame: 74,
    w: 78,
    h: 96,
    anchor: "top-left",
    minSegmentWidth: 112,
    clearance: { w: 70, h: 86 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.08
  },
  {
    id: "timber-hanging-tags-cables",
    material: "wood-archive",
    category: "overhang",
    frame: 75,
    w: 94,
    h: 100,
    anchor: "top-left",
    minSegmentWidth: 128,
    clearance: { w: 84, h: 90 },
    densities: ["medium", "high"],
    weight: 2,
    depthOffset: 0.08
  },
  {
    id: "timber-hanging-lamps",
    material: "wood-archive",
    category: "overhang",
    frame: 76,
    w: 92,
    h: 106,
    anchor: "top-left",
    minSegmentWidth: 128,
    clearance: { w: 82, h: 96 },
    densities: ["high"],
    weight: 2,
    depthOffset: 0.08
  },
  {
    id: "timber-carved-panel",
    material: "wood-archive",
    category: "wall-decal",
    frame: 77,
    w: 124,
    h: 122,
    anchor: "wall-left",
    minSegmentWidth: 136,
    clearance: { w: 112, h: 110 },
    densities: ["medium", "high"],
    weight: 3,
    depthOffset: 0.05
  }
] as const satisfies readonly TerrainDecorPropDefinition[];

export const allTerrainDecorProps = [
  ...gardenTerrainDecorProps,
  ...rainhouseTerrainDecorProps,
  ...cryoTerrainDecorProps,
  ...woodArchiveTerrainDecorProps
] as const satisfies readonly TerrainDecorPropDefinition[];

export const terrainDecorPropsForMaterial = (material: TerrainMaterial): readonly TerrainDecorPropDefinition[] =>
  allTerrainDecorProps.filter((prop) => prop.material === material);
